#!/usr/bin/env ruby
basedir = File.dirname(File.expand_path(__FILE__))

md5sum = (`which md5 2> /dev/null` || `which md5sum 2> /dev/null`).strip
if File.basename(md5sum).strip == 'md5'
  md5sum += ' -r'
end

Dir[File.join basedir, '/.*'].each do | file |
  basename = File.basename(file)
  next if ['..', '.', '.git'].include?(basename)

  old_conf = file
  new_conf = "#{ENV['HOME']}/#{basename}"

  puts [basename.ljust(23), '=>', "~/#{basename}"].join(' ')
  if File.symlink?(new_conf) || File.exist?(new_conf)
    `rm -rf #{new_conf}`
  end
  `ln -s #{old_conf} #{new_conf}`
end

